<?php
$z[0]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename/]\">[field:typename/]</a>",169,278);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename/]\">[field:typename/]</a>",280,390);
$z[1][4]['typeid']="17";
$z[2]=Array("type","<a href=\"[field:typelink /]\"  title=\"[field:typename/]\">[field:typename/]</a>",392,501);
$z[2][4]['typeid']="6";
$z[3]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",722,949);
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='col'>~typename~</a></li>";
$z[4]=Array("arclist","\r\n      <li><img src=\"[field:litpic/]\"  alt=\"[field:title/]\" title=\"[field:title/]\"/></li>\r\n      ",1058,1200);
$z[4][4]['row']="3";
$z[4][4]['typeid']="7";

?>