<?php
$z[0]=Array("field","",141,199);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n        <dd><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n        ",214,355);
$z[1][4]['type']="son";
$z[2]=Array("global","",576,598);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",671,692);
$z[3][4]['name']="cfg_sj";
$z[4]=Array("global","",720,741);
$z[4][4]['name']="cfg_yx";
$z[5]=Array("global","",771,793);
$z[5][4]['name']="cfg_add";

?>