<article id="featPost[field:global.autoindex/]" class="case-post clearfix">
					<div class="special clearfix">	
					
		
		<figure><a href="[field:arcurl/]" title="[field:fulltitle/]"><img src="[field:picname/]" alt="[field:fulltitle/]" />
		</a></figure>
		
		<header><h2><a href="[field:arcurl/]">[field:title/]</a></h2></header>
		<span class="post"><time pubdate="pubdate" datetime="2013-03-05"><b>[field:pubdate function=MyDate('y-m-d',@me)/]</b></time> <i>|</i> 位置 > <a>[field:typename /]</a> 
</span>
		<p>[field:description function="cn_substr(@me,180)"/]...</p>  
		<a href="[field:arcurl/]" class="cta" title="查看全文">查看全文</a>
		

					</div>
				</article>