<article class="news-post">
      <figure><a href="[field:arcurl/]" title="[field:fulltitle/]"><img src="[field:picname/]"  alt="[field:fulltitle/]" /> </a></figure>
      <header>
        <h2><a href="[field:arcurl/]">[field:title/]...</a></h2>
      </header>
      <span class="post">
      <time pubdate="pubdate" datetime="[field:pubdate function=MyDate('y-m-d',@me)/]"><b>[field:pubdate function=MyDate('y-m-d',@me)/]</b></time>
      <i>|</i> 位置 > [field:typelink/] </span>
      <p>[field:description function="cn_substr(@me,100)"/]...</p>
      <a href="[field:arcurl/]" class="cta">查看全文</a> </article>