<?php
$z[0]=Array("arcurl","",52,67);
$z[1]=Array("fulltitle","",76,94);
$z[2]=Array("picname","",106,122);
$z[3]=Array("fulltitle","",130,148);
$z[4]=Array("arcurl","",205,220);
$z[5]=Array("title","",222,236);
$z[6]=Array("pubdate","",334,379);
$z[6][4]['function']="MyDate('y-m-d',@me)";
$z[7]=Array("pubdate","",384,429);
$z[7][4]['function']="MyDate('y-m-d',@me)";
$z[8]=Array("typelink","",466,483);
$z[9]=Array("description","",502,552);
$z[9][4]['function']="cn_substr(@me,100)";
$z[10]=Array("arcurl","",576,591);

?>