<?php
$z[0]=Array("global","",21,46);
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",145,160);
$z[2]=Array("fulltitle","",169,187);
$z[3]=Array("picname","",199,215);
$z[4]=Array("fulltitle","",222,240);
$z[5]=Array("arcurl","",290,305);
$z[6]=Array("title","",307,321);
$z[7]=Array("pubdate","",411,456);
$z[7][4]['function']="MyDate('y-m-d',@me)";
$z[8]=Array("typename","",489,507);
$z[9]=Array("description","",528,578);
$z[9][4]['function']="cn_substr(@me,180)";
$z[10]=Array("arcurl","",600,615);

?>