<?php
$z[0]=Array("field","",302,321);
$z[0][4]['name']="title";
$z[1]=Array("global","",322,348);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",389,411);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",451,502);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1976,2013);
$z[4][4]['filename']="header.htm";
$z[5]=Array("field","",2308,2364);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[6]=Array("field","",2369,2421);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("type"," <a href='[field:typeurl /]'>[field:typename /]</a> ",2451,2526);
$z[8]=Array("field","",2558,2585);
$z[8][4]['name']="phpurl";
$z[9]=Array("field","",2609,2632);
$z[9][4]['name']="id";
$z[10]=Array("field","",2637,2661);
$z[10][4]['name']="mid";
$z[11]=Array("prenext","",2730,2755);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",2761,2787);
$z[12][4]['get']="next";
$z[13]=Array("field","",2808,2827);
$z[13][4]['name']="title";
$z[14]=Array("field","",2839,2857);
$z[14][4]['name']="body";
$z[15]=Array("include","",3108,3145);
$z[15][4]['filename']="footer.htm";

?>