<?php
$z[0]=Array("field","",270,289);
$z[0][4]['name']="title";
$z[1]=Array("global","",290,316);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",357,379);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",419,470);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1850,1887);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",4244,4281);
$z[5][4]['filename']="footer.htm";

?>