<?php
$z[0]=Array("arcurl","",52,67);
$z[1]=Array("fulltitle","",76,94);
$z[2]=Array("picname","",106,122);
$z[3]=Array("fulltitle","",130,148);
$z[4]=Array("arcurl","",198,213);
$z[5]=Array("title","",215,229);
$z[6]=Array("pubdate","",307,352);
$z[6][4]['function']="MyDate('y-m-d',@me)";
$z[7]=Array("pubdate","",357,402);
$z[7][4]['function']="MyDate('y-m-d',@me)";
$z[8]=Array("typelink","",432,449);
$z[9]=Array("description","",465,515);
$z[9][4]['function']="cn_substr(@me,100)";
$z[10]=Array("arcurl","",535,550);

?>