<?php
$z[0]=Array("arclist","\r\n			    		<dd><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]...</a></dd>\r\n                		",564,747);
$z[0][4]['typeid']="9,10";
$z[0][4]['row']="4";
$z[0][4]['titlelen']="30";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("arclist","\r\n                		<dd><a href=\"[field:arcurl/]\" >[field:title/]...</a></dd>\r\n                		",842,1018);
$z[1][4]['typeid']="4,5";
$z[1][4]['row']="4";
$z[1][4]['titlelen']="30";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("flink","[field:link /]",2195,2256);
$z[2][4]['linktype']="2";
$z[2][4]['row']="50";
$z[3]=Array("flink","[field:link /]",2256,2318);
$z[3][4]['type']="image";
$z[3][4]['row']="50";

?>