<?php
$z[0]=Array("global","",267,293);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",365,395);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",432,459);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1986,2023);
$z[3][4]['filename']="header.htm";
$z[4]=Array("arclist","\r\n    <article class=\"news-post\">\r\n      <figure><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"><img src=\"[field:picname/]\"  alt=\"[field:fulltitle/]\" /> </a></figure>\r\n      <header>\r\n        <h2><a href=\"[field:arcurl/]\">[field:title/]...</a></h2>\r\n      </header>\r\n      <span class=\"post\">\r\n      <time pubdate=\"pubdate\" datetime=\"[field:pubdate function=MyDate('y-m-d',@me)/]\"><b>[field:pubdate function=MyDate('y-m-d',@me)/]</b></time>\r\n      <i>|</i> 位置 > [field:typelink/] </span>\r\n      <p>[field:description function=\"cn_substr(@me,100)\"/]...</p>\r\n      <a href=\"[field:arcurl/]\" class=\"cta\">查看全文</a> </article>\r\n    ",10666,11389);
$z[4][4]['typeid']="4,5";
$z[4][4]['row']="1";
$z[4][4]['titlelen']="32";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("include","",11790,11827);
$z[5][4]['filename']="footer.htm";

?>